### ISSUE TITLE
Running on Android/IOS devices?

### ISSUE THREAD

**Issue by xuguozhi** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#3]
Hi @YonghaoHe you have done a great job! Any plans to port this project to Android or IOS devices? Demos are needed!

**Comment by YonghaoHe** [comment]
> Hi @YonghaoHe you have done a great job! Any plans to port this project to Android or IOS devices? Demos are needed!

@xuguozhi The main steps porting the project to Android or IOS include:

- choose a SOTA inference engine, like NCNN, MNN or Tegine, then transplant the code to that engine

- also rewrite the post-processing code (like NMS and feature map processing) using C++ 

- write the native API to use the functionalities

In fact, in mobile devices, the model can be greatly optimized by prunning, compression, and selecting proper input size according to your application.

Currently, I have planned to evaluate latency on ARM (MNN&Tegine), NCS1&2, produce models for other tasks, like head detection, pedestrian detection... So some steps listed above are not covered due to limited time and ennergy. In the future, these requirements will be done. Any contributions are welcome.

**Comment by xuguozhi** [comment]
Thanks, I will try NCNN o MNN.

**Comment by gwestner94** [comment]
Hi @xuguozhi,
did you try running the model with NCNN/MNN in C++?
Is there any experience you can share?

Thank you!
